email  = "aruul.bhagkya@qxf2.com"
password = "AganSarwin@2021"
url="https://stackoverflow.com/questions/67902537/python-selenium-change-url-date"
title="python-selenium-change-url"
description="python-selenium-change-url"
runtime="15"
category="currentweek"
search="python"